### ISSUE TITLE
Adding documentation for pre-requisites

### ISSUE THREAD

**Issue by AyushyaChitransh** [rogeruiz/tick#13]
## Detailed Description
Provide more information regarding how to use the project and what are the requisites for using this.

## Context
I am fairly new to rust.  But newer to postgresql. So I need some direction regarding how to setup the database. Some searching showed me how to install postgresql, but am still looking for following answers:

 - Is the DB created by itself or do I need to create it?
 - Where would I find the DB?
 - Database URL: It should start with `postgres://`. This probably means I need to run postgresql separately.

## Possible Implementation
It would be helpful if there were some directions regarding setting up and using the database of project.

## Your Environment

Installed postgresql via: `brew install prostgersql`

**Comment by rogeruiz** [comment]
Hey @AyushyaChitransh,

Sorry for the delay. Hopefully your Rust journey has continued. I'm addressing some of your questions with better documentation and easier UX for Tick in another (#14) PR. If you would like to check out that `add-testing` branch and take it for a spin, it would be much appreciated. 

Here's a [Dockerfile](https://gist.github.com/829516010b42962a2e4c5097b4f6caa1) you can use as a starting point for using that branch to build Tick for an Ubuntu machine. You can also compile it from source locally using `cargo build --release` and follow the steps in the docs for setting up your environment. I have only used Linux or macOS for setting it up, so any patches for supporting Windows would be much appreciated.

### Answers to your questions

> Is the DB created by itself or do I need to create it?

In Tick 1.0, the database will be created and fully migrated to a working state automatically. For the code that's on the `main` branch, you will need to install `diesel_cli` and run `diesel setup --database-url /path/to/tick/database/file.db` to run the initial migration. After that, the binary that gets built with `cargo build --release` will be able to use that database by setting the `${DATABASE_URL}` environment variable when running Tick.

> Where would I find the DB?

The database is set with the environment variable `$TICK_DATABASE_FILE`. Just make sure that it's a full path to your SQLite 3+ database. There's no need to setup an external database such as PostgreSQL or MySQL although Diesel supports those. Tick is only concerned with being able to run embedded on a system with SQLite 3+ installed. 

> Database URL: It should start with postgres://. This probably means I need to run postgresql separately.

Sorry for this confusing point. The environment variable `$DATABASE_URL` is the default in Diesel, the ORM I'm using, and it's not appropriate for this project. I've updated it to be `$TICK_DATABASE_FILE` for now. In a future Tick release, it will be a configuration file used to setup the path for the database and possibly support multiple databases.

---

Thanks and again sorry for the delay response.

**Comment by rogeruiz** [comment]
Closed by #14
